[build]
builder = "NIXPACKS"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
